version: 0.0.3
server:
  address: 127.0.0.1
  port: 9201
  password: !!str ikun520
helps:
  - \t __file__ --version 获取当前MPI版本
  - \t __file__ --help 获取MPI帮助
  - \t __file__ --console 打开MPI交互式命令行
  - \t __file__ --start 启动MPI Python端接口